package common

import (
	"fmt"
	"testing"
)

func TestParseAlbumTitleAndSubtitle(t *testing.T) {
	tests := []struct {
		name            string
		input           string
		wantTitle       string
		wantSubtitle    string
		wantTokenResult bool
		tokenInput      string
	}{
		{
			name:            "remastered version",
			input:           "Daydream Nation (2012 Remastered Version)",
			wantTitle:       "Daydream Nation",
			wantSubtitle:    "2012 Remastered Version",
			wantTokenResult: true,
			tokenInput:      "2012 Remastered Version",
		},
		{
			name:            "anniversary and remastered",
			input:           "The Dark Side of the Moon (50th Anniversary) [Remastered]",
			wantTitle:       "The Dark Side of the Moon",
			wantSubtitle:    "(50th Anniversary) [Remastered]",
			wantTokenResult: true,
			tokenInput:      "50th Anniversary",
		},
		{
			name:            "regional version",
			input:           "认了吧 (Hong Kong Version)",
			wantTitle:       "认了吧",
			wantSubtitle:    "Hong Kong Version",
			wantTokenResult: true,
			tokenInput:      "Hong Kong Version",
		},
		{
			name:            "remastered year",
			input:           "胡思乱想 (Remastered 2019)",
			wantTitle:       "胡思乱想",
			wantSubtitle:    "Remastered 2019",
			wantTokenResult: true,
			tokenInput:      "Remastered 2019",
		},
		{
			name:            "live",
			input:           "为你盛开-许巍《无尽光芒》巡回演唱会现场纪念 (Live)",
			wantTitle:       "为你盛开-许巍《无尽光芒》巡回演唱会现场纪念",
			wantSubtitle:    "Live",
			wantTokenResult: true,
			tokenInput:      "Live",
		},
		{
			name:            "bonus track version",
			input:           "Who Are You (Bonus Track Version)",
			wantTitle:       "Who Are You",
			wantSubtitle:    "Bonus Track Version",
			wantTokenResult: true,
			tokenInput:      "Bonus Track Version",
		},
		{
			name:            "super deluxe edition",
			input:           "Wolfmother (10th Anniversary Deluxe Edition)",
			wantTitle:       "Wolfmother",
			wantSubtitle:    "10th Anniversary Deluxe Edition",
			wantTokenResult: true,
			tokenInput:      "10th Anniversary Deluxe Edition",
		},
		{
			name:            "live venue",
			input:           "Affirmations (Live at Blue Note New York)",
			wantTitle:       "Affirmations",
			wantSubtitle:    "Live at Blue Note New York",
			wantTokenResult: true,
			tokenInput:      "Live at Blue Note New York",
		},
		{
			name:            "lowercase deluxe edition",
			input:           "Abbey Road (super deluxe edition)",
			wantTitle:       "Abbey Road",
			wantSubtitle:    "super deluxe edition",
			wantTokenResult: true,
			tokenInput:      "super deluxe edition",
		},
		{
			name:            "remix",
			input:           "A Momentary Lapse of Reason (2019 Remix)",
			wantTitle:       "A Momentary Lapse of Reason",
			wantSubtitle:    "2019 Remix",
			wantTokenResult: true,
			tokenInput:      "2019 Remix",
		},
		{
			name:            "multiple segments",
			input:           "(What's the Story) Morning Glory? [Deluxe Edition] [Remastered]",
			wantTitle:       "(What's the Story) Morning Glory?",
			wantSubtitle:    "[Deluxe Edition] [Remastered]",
			wantTokenResult: true,
			tokenInput:      "Deluxe Edition",
		},
		{
			name:            "mixed brackets",
			input:           "2112 (Deluxe Edition) [2012 Remaster]",
			wantTitle:       "2112",
			wantSubtitle:    "(Deluxe Edition) [2012 Remaster]",
			wantTokenResult: true,
			tokenInput:      "2012 Remaster",
		},
		{
			name:            "anniversary super deluxe",
			input:           "All That You Can't Leave Behind (20th Anniversary Super Deluxe Edition)",
			wantTitle:       "All That You Can't Leave Behind",
			wantSubtitle:    "20th Anniversary Super Deluxe Edition",
			wantTokenResult: true,
			tokenInput:      "20th Anniversary Super Deluxe Edition",
		},
		{
			name:            "formal title with leading bracket is preserved",
			input:           "(Pronounced 'Lĕh-'nérd 'Skin-'nérd)",
			wantTitle:       "(Pronounced 'Lĕh-'nérd 'Skin-'nérd)",
			wantSubtitle:    "",
			wantTokenResult: false,
			tokenInput:      "Pronounced 'Lĕh-'nérd 'Skin-'nérd",
		},
		{
			name:            "non subtitle bracket is preserved",
			input:           "The Age of Adz (Act III)",
			wantTitle:       "The Age of Adz (Act III)",
			wantSubtitle:    "",
			wantTokenResult: false,
			tokenInput:      "Act III",
		},
		{
			name:            "non subtitle bracket is preserved",
			input:           "Best Selection Songs 2004~2018 (Volume.2)",
			wantTitle:       "Best Selection Songs 2004~2018 (Volume.2)",
			wantSubtitle:    "",
			wantTokenResult: false,
			tokenInput:      "Volume.2",
		},
		{
			name:            "non subtitle bracket is preserved",
			input:           "Harvest (50th Anniversary Edition)",
			wantTitle:       "Harvest",
			wantSubtitle:    "50th Anniversary Edition",
			wantTokenResult: true,
			tokenInput:      "50th Anniversary Edition",
		},
		{
			name:            "non subtitle bracket is preserved",
			input:           "Harvest (50th Anniversary Edition)",
			wantTitle:       "Harvest",
			wantSubtitle:    "50th Anniversary Edition",
			wantTokenResult: true,
			tokenInput:      "50th Anniversary Edition",
		},
	}

	for _, tc := range tests {
		t.Run(
			tc.name, func(t *testing.T) {
				gotTitle, gotSubtitle := ParseAlbumTitleAndSubtitle(tc.input)
				if gotTitle != tc.wantTitle || gotSubtitle != tc.wantSubtitle {
					t.Fatalf(
						"ParseAlbumTitleAndSubtitle(%q) = (%q, %q), want (%q, %q)",
						tc.input,
						gotTitle,
						gotSubtitle,
						tc.wantTitle,
						tc.wantSubtitle,
					)
				}
			},
		)
	}
}

func TestParseAlbumTitleAndSubtitle1(t *testing.T) {
	names := []string{
		"2112 (Deluxe Edition)",
		"2112 (Deluxe Edition) [2012 Remaster]",
		"21st Century Breakdown (Deluxe Edition)",
		"90125 (Deluxe Edition)",
		"A Colores (Expanded Edition)",
		"A Momentary Lapse of Reason (2019 Remix)",
		"A Night at the Opera (Deluxe Edition)",
		"Abbey Road (2019 Mix)",
		"Abbey Road (super deluxe edition)",
		"Achtung Baby (20th Anniversary Deluxe Edition)",
		"Affirmations (Live at Blue Note New York)",
		"All Things Must Pass (2014 Remaster)",
		"AM (Live EP Bonus Edition)",
		"And Close As This (2007 Remaster)",
		"At War with the Mystics (Deluxe Version)",
		"Automatic For The People (25th Anniversary Edition) [2017 Remaster]",
		"Ballads (Deluxe Edition)",
		"Beautiful Boy (Original Motion Picture Soundtrack)",
		"Beauty And The Beat! (Expanded Edition)",
		"Best of Country & Western (2024 Remasters)",
		"Bleach (20th Anniversary Deluxe Edition)",
		"Bleed American (Deluxe Edition)",
		"Bobby Charles (Bonus Track Version)",
		"Breakfast in America (Deluxe Edition)",
		"Breakfast in America (Deluxe Edition) [2010 Remaster]",
		"Bridges To Babylon (2009 Remaster)",
		"Brother Where You Bound (Remastered)",
		"Brothers In Arms (Remastered 1996)",
		"Building The Perfect Beast (Remastered 2024)",
		"Californication (Remastered)",
		"Camel (Expanded Edition)",
		"Cherry Tree (2021 Remaster)",
		"Close to the Edge (Deluxe Edition)",
		"Close to the Edge (Super Deluxe Edition)",
		"Coles Corner (20th Anniversary Deluxe Edition)",
		"Come Away With Me (Super Deluxe Edition)",
		"Communiqué (Remastered)",
		"Corinne Bailey Rae (Deluxe Edition)",
		"Crime of the Century (Deluxe Edition) [2014 Remaster]",
		"Crosby, Stills & Nash (Deluxe Version)",
		"Dance Into the Light (Deluxe Edition)",
		"David Bowie (aka Space Oddity) [2015 Remaster]",
		"Daydream Nation (2012 Remastered Version)",
		"Déjà Vu (50th Anniversary Deluxe Edition)",
		"Different World (Expanded Version)",
		"Dire Straits (Remastered)",
		"Dirt (Remastered)",
		"Don't Go To Strangers (Rudy Van Gelder Remaster)",
		"Echoes Of Life (Deluxe Edition)",
		"Ege Bamyasi (Remastered)",
		"Ellington (Live)",
		"Embryonic (Deluxe Version)",
		"Emergency On Planet Earth (Remastered)",
		"Empire (Remastered) [Expanded Edition]",
		"Even In the Quietest Moments... (Remastered)",
		"Everybody's in Show-Biz (Deluxe) [2022 Remaster]",
		"Famous Last Words (Remastered)",
		"Filth (Deluxe Edition)",
		"Giant Steps (60th Anniversary Super Deluxe Edition) [2020 Remaster]",
		"Gone to Earth (Remastered 2003)",
		"Greatest Hits (2024 Remaster)",
		"High Violet (Expanded Edition)",
		"Hollywood: A Story of a Dozen Roses (Deluxe Version)",
		"Hot Space (Deluxe Edition)",
		"Hotel California (40th Anniversary Expanded Edition)",
		"Houses of the Holy (Deluxe Edition)",
		"Hybrid Theory (Deluxe Edition)",
		"I/O (Bright-Side and Dark-Side Mixes)",
		"Idlewild South (Deluxe Edition)",
		"In Between (Deluxe Edition)",
		"In the Court of the Crimson King (Expanded Edition)",
		"In the Wake of Poseidon (Expanded Edition)",
		"In Through the Out Door (Deluxe Edition)",
		"Invisible Touch (2007 Remaster)",
		"Islands (Expanded Edition)",
		"It's Hard (Bonus Track Version)",
		"Jazz (Deluxe Edition)",
		"L.A. Woman (50th Anniversary Deluxe Edition)",
		"La La Land (Original Motion Picture Soundtrack)",
		"Larks' Tongues In Aspic (Expanded Edition)",
		"Led Zeppelin II (Deluxe Edition)",
		"Led Zeppelin III (Deluxe Edition)",
		"Led Zeppelin IV (Deluxe Edition)",
		"Legacy: the Creedence Clearwater Revival years (John's Version)",
		"Lenka (Expanded Edition)",
		"Listen to Eason Chan (Remastered 2019)",
		"Little Girl Blue (2021 - Stereo Remaster)",
		"Love Is a Four Letter Word (Deluxe Version)",
		"Love Over Gold (Remastered)",
		"Made In Heaven (Deluxe Edition)",
		"Maim That Tune (2025 30th Anniversary Remaster)",
		"Mars Audiac Quintet (Expanded Edition)",
		"Master of Puppets (Remastered)",
		"McCartney (Archive Collection Special Edition) [2011 Remaster]",
		"Meddle (2016 Remaster)",
		"Misplaced Childhood (Deluxe Edition) [Remastered]",
		"MODERAT FM (DJ Mix)",
		"Moondance (Expanded Edition)",
		"Morrison Hotel (50th Anniversary Deluxe Edition)",
		"Move Your Hand (Live)",
		"Moving Pictures (Remastered)",
		"My Generation (Stereo Version) [Deluxe Version]",
		"No More Drama (Version 2)",
		"No More Tears (Bonus Track Version)",
		"Non-Stop Ecstatic Dancing (Deluxe Edition)",
		"Ö (Bonus Version)",
		"On Every Street (Remastered)",
		"Ones & Twos (Expanded Edition)",
		"Pas de géant (Version deluxe)",
		"Peng! (2018 Remaster)",
		"Peter Gabriel 1: Car (Remastered)",
		"Peter Gabriel 3: Melt (Remastered)",
		"Physical Graffiti (Deluxe Edition)",
		"Pink Floyd at Pompeii - MCMLXXII (2025 Mix)",
		"Privateering (Deluxe Version)",
		"Quadrophenia (2013 Remaster)",
		"Quadrophenia (Deluxe Version)",
		"Rain Tree Crow (Remastered)",
		"Rashida (Expanded Edition)",
		"Reckless (30th Anniversary) [Deluxe Edition]",
		"Red (Expanded Edition)",
		"Reggatta De Blanc (Remastered 2003)",
		"Remain In Light (Deluxe Version)",
		"Rumours (Super Deluxe Edition)",
		"Rush (Remastered 2013)",
		"Secrets of the Beehive (Remastered 2003)",
		"Selling England By the Pound (2007 Stereo Mix)",
		"Sixteen Stone (Remastered)",
		"Slippery When Wet (Deluxe Edition)",
		"Some Girls (Deluxe Edition with Bonus Video) [2011 Remaster]",
		"Songs of Innocence (Deluxe Edition)",
		"Soulville (2025 Remastered Version)",
		"Spiderland (Remastered)",
		"Stand Up (2010 Collector's Edition) [2001 Remaster]",
		"Starless and Bible Black (Expanded Edition)",
		"Station to Station (2016 Remaster)",
		"Sticky Fingers (Deluxe Edition) [2015 Remaster]",
		"Synchronicity (Remastered 2003)",
		"Ta Min Vals / Sjunger Leonard Cohen (Bonus Track Version)",
		"Tango in the Night (2017 Remaster) [Deluxe Edition]",
		"Tattoo You (Deluxe Edition)",
		"The Ape of Naples (2022 Remastered Version)",
		"The Band (Remastered)",
		"The Best of Acoustic Jethro Tull (Remastered)",
		"The Branches (Deluxe Edition)",
		"The Dark Side of the Moon (50th Anniversary) [Remastered]",
		"The Doors (50th Anniversary Deluxe Edition)",
		"The Endless River (Deluxe Edition)",
		"The Hissing of Summer Lawns (2022 Remaster)",
		"The Information (Bonus Video Version)",
		"The Queen Is Dead (Deluxe Edition)",
		"The Rise and Fall of Ziggy Stardust and the Spiders from Mars (2012 Remaster)",
		"The Smashing Machine (Original Motion Picture Soundtrack)",
		"The Snow Goose (Expanded Edition)",
		"The Soft Parade (50th Anniversary Deluxe Edition)",
		"The Velvet Underground & Nico 45th Anniversary (Deluxe Edition)",
		"The Who Hits 50! (Deluxe Edition)",
		"The Yes Album (Super Deluxe Edition)",
		"Think Twice (Remixes)",
		"THRAK (Expanded Edition)",
		"Tormato (Deluxe Edition)",
		"Tourist (Remastered) [Deluxe Version]",
		"TRON: Ares (Original Motion Picture Soundtrack)",
		"Urban Hymns (Deluxe / Remastered 2016)",
		"Use Your Illusion II (Deluxe Edition)",
		"v2.0 (Deluxe Edition)",
		"Veckatimest (Deluxe Version)",
		"WE ARE (The Deluxe Edition)",
		"What We Saw from the Cheap Seats (Deluxe Version)",
		"Whenever You Need Somebody (Deluxe Edition - 2022 Remaster)",
		"Where I'm Meant To Be (Deluxe Edition)",
		"WHO (Deluxe Edition)",
		"Who Are You (Bonus Track Version)",
		"Who Is Jill Scott?: Words and Sounds, Vol. 1 (2020 Remastered)",
		"Who's Next (Bonus Track Version)",
		"Who's Next (Deluxe Edition)",
		"Wildflowers & All the Rest (Super Deluxe Edition)",
		"Wind & Wuthering (2007 Remaster)",
		"Wolfmother (10th Anniversary Deluxe Edition)",
		"X (Deluxe Edition)",
		"XO (Deluxe Edition)",
		"Yes (Deluxe Edition)",
		"为你盛开-许巍《无尽光芒》巡回演唱会现场纪念 (Live)",
		"关于她的爱情故事 (2021 Remaster)",
		"胡思乱想 (Remastered 2019)",
		"认了吧 (Hong Kong Version)",
		"The Age of Adz (Act III)",
		"Best Selection Songs 2004~2018 (Volume.2)",
	}

	for _, name := range names {
		title, subtitle := ParseAlbumTitleAndSubtitle(name)
		if len(subtitle) == 0 {
			fmt.Println("转换前:" + name)
			fmt.Println("转换后title:" + title)
			fmt.Println("转换后subtitle:不存在")
			fmt.Println("==")
		} else {
			fmt.Println("转换前:" + name)
			fmt.Println("转换后title:" + title)
			fmt.Println("转换后subtitle:" + subtitle)
			fmt.Println("==")

		}
	}
}
